# drone
pipeline:
 step1:
  image: quodatum/basexhttp:BaseX951
  commands:
  - echo hello
  - echo world 
    - pwd
    - ls
 step2:
  image: quodatum/basexhttp:BaseX951
  commands:
    - pwd
    - ls    
